version: '3.8'

services:
  people-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: people-manager-crm
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload in development
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/setup/status", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
